name: Deploy Auth Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          timeout: 60s
          command_timeout: 10m
          script: |
            echo "🚀 Starting Marmara APIs Server CI..."
            
            # Install bun if not available
            if [ ! -f ~/.bun/bin/bun ]; then
              echo "🔧 Installing bun..."
              curl -fsSL https://bun.sh/install | bash
            fi
            
            # Navigate to auth service folder
            echo "📂 Navigating to auth service..."
            cd ~/Apps/marmara-api/
            
            # Pull new changes
            echo "📥 Pulling new changes..."
            git fetch origin main
            git reset --hard origin/main
            
            # Install dependencies with bun
            echo "📦 Installing dependencies with bun..."
            ~/.bun/bin/bun i
            
            # Generate Prisma client
            echo "🔧 Generating Prisma client..."
            npx prisma db push
            
            
            
            # Build application
            echo "🏗️ Building application..."
            npm run build
            
            # Restart PM2 process
            echo "🔄 Restarting PM2 process..."
            pm2 restart marmara-api
            
            echo "🎉 Marmara APIs Server deployment completed successfully!"

  notify:
    name: Send Deployment Status
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always()
    
    steps:
      - name: Get Commit Message
        id: commit
        run: |
          echo "message=$(curl -s -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }} \
            | jq -r '.commit.message' | head -n 1)" >> $GITHUB_OUTPUT

      - name: Send Success Message
        if: needs.deploy.result == 'success'
        run: |
          MSG="Marmara APIs Server Deployed Successfully! 🎉 Details: Commit ${GITHUB_SHA::7} - ${GITHUB_REF_NAME} by ${GITHUB_ACTOR}. Service is now live!"
          ENCODED_MSG=$(echo "$MSG" | perl -p -e 's/([^A-Za-z0-9])/sprintf("%%%02X", ord($1))/seg')
          curl -s "https://api.callmebot.com/whatsapp.php?phone=255710097350&text=$ENCODED_MSG&apikey=6668493"

      - name: Send Failure Message
        if: needs.deploy.result == 'failure'
        run: |
          MSG="Marmara APIs Server Deployment Failed! ❌ Details: Commit ${GITHUB_SHA::7} - ${GITHUB_REF_NAME} by ${GITHUB_ACTOR}. Check GitHub Actions logs."
          ENCODED_MSG=$(echo "$MSG" | perl -p -e 's/([^A-Za-z0-9])/sprintf("%%%02X", ord($1))/seg')
          curl -s "https://api.callmebot.com/whatsapp.php?phone=255710097350&text=$ENCODED_MSG&apikey=6668493"